---
# See: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "client"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "server"
    update_schedule: "live"
  - package_manager: "javascript"
    directory: "deploy"
    update_schedule: "live"
